{% set version = "3.9.0" %}

package:
  name: maven
  version: {{ version }}

source:
  fn: apache-maven-{{ version }}-bin.tar.gz
  url: https://archive.apache.org/dist/maven/maven-3/{{ version }}/binaries/apache-maven-{{ version }}-bin.tar.gz
  sha256: b118e624ec6f7abd8fc49e6cb23f134dbbab1119d88718fc09d798d33756dd72

build:
  number: 0

requirements:
  run:
    - openjdk

test:
  commands:
    # This test segfaults qemu on ppc64le
    - mvn -v  # [not ppc64le]

about:
  home: https://maven.apache.org
  license: Apache-2.0
  license_file: LICENSE
  summary: A software project management and comprehension tool.
  description: |
    Apache Maven is a software project management and comprehension tool.
    Based on the concept of a project object model (POM), Maven can manage
    a project's build, reporting and documentation from a central piece of information.

extra:
  recipe-maintainers:
    - johanneskoester
    - hadim
    - mariusvniekerk
    - matthiasdiener
