travis:
  secure:
    BINSTAR_TOKEN: yV44EGwiTKg6qLP/BrPpTLAte15SD0xBhVHYyAaN5LTt2gcbVIqjlgc1muXaFLyx+VDK+12WZO50w9MXva/whBJwHg/BBctMoTrQCvjy+q9SJO4Iqq3lpD/S30tM5cevB0OjZimTLwafYYQhz3o96A0iqpzG2I3ICqT1DBJKV+e3HYzpiQCZkVACm65+S1PE4oPE4kbenHbngCzWvcaKvwMm8O3s5On3yQlOff7wGaqdQRosomrSts8EUnkojb3PAgXCvpfSz3QSKKx6lA/WYuljDcjyFNmJyFrKJy9hEBjDHi516zY+nb39bQnM22THRUbgAp4CiIeW2w9wi7YrUGESnRt5AS3i9TOXYWAyb79LExib7KcWyQZQoNeF1GkOSMvuYs8ER+emnmzAxBL1S6lE4YO96kegAkrYBJ/bK++pQc3P7sygXsvRx5y9tGv7ld5i8OSoRw6hDZTMGSoIU+cswJmWxTq95+pPr2CepVtuz1bTaHDaodrXArLAdUD2Cy0KfRnsChoVEaWg61Mso/a9TFF3ZaXjqH9f/KaDU3eOEHKIhM1mQpvsPIzRdwHS4HhccnNcdPLvaFxhhMVivgzrKQa01A8DecMaREa+L66sioebhlR9s6uAUeii6L/Mh9+usbo3FmhLo/OFuyOKjU+o7CZJa36pW4eotCu/u2c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
